### ISSUE TITLE
AttributeError: 'BECO' object has no attribute 'to'

### ISSUE THREAD

**Issue by jjxyhb** [NUST-Machine-Intelligence-Laboratory/SSC#3]
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/ssc/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/dell/CV408/hb/SSC/segmentation/main.py", line 262, in main_worker
    model.to(device)
AttributeError: 'BECO' object has no attribute 'to'

**Comment by chentao2016** [comment]
The segmentation code is directly borrowed from BECO [https://github.com/ShenghaiRong/BECO]. You can refer to the project to ensure that the environment is ok.
